import { nanoid } from 'nanoid';
import catPicture from 'images/example/cat.jpg';

const items = [
    {
        id: nanoid(),
        category: 'sell',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute cat looking for a home',
        favorite: true,
        image: catPicture,
    },
    {
        id: nanoid(),
        category: 'sell',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute cat looking for a home',
        favorite: false,
        image: catPicture,
    },
    {
        id: nanoid(),
        category: 'sell',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute cat looking for a home',
        favorite: true,
        image: catPicture,
    },
    {
        id: nanoid(),
        category: 'sell',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute cat looking for a home',
        favorite: false,
        image: catPicture,
    },
    {
        id: nanoid(),
        category: 'sell',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute cat looking for a home',
        favorite: true,
        image: catPicture,
    },
    {
        id: nanoid(),
        category: 'sell',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute cat looking for a home',
        favorite: false,
        image: catPicture,
    },
    {
        id: nanoid(),
        category: 'sell',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute cat looking for a home',
        favorite: false,
        image: catPicture,
    },
    {
        id: nanoid(),
        category: 'sell',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute cat looking for a home',
        favorite: true,
        image: catPicture,
    },
    {
        id: nanoid(),
        category: 'sell',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute cat looking for a home',
        favorite: true,
        image: catPicture,
    },
    {
        id: nanoid(),
        category: 'sell',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute cat looking for a home',
        favorite: true,
        image: catPicture,
    },
    {
        id: nanoid(),
        category: 'sell',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute cat looking for a home',
        favorite: true,
        image: catPicture,
    },
    {
        id: nanoid(),
        category: 'sell',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute cat looking for a home',
        favorite: false,
        image: catPicture,
    },
    {
        id: nanoid(),
        category: 'sell',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute cat looking for a home',
        favorite: true,
        image: catPicture,
    },
    {
        id: nanoid(),
        category: 'sell',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute cat looking for a home',
        favorite: false,
        image: catPicture,
    },
    {
        id: nanoid(),
        category: 'sell',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute cat looking for a home',
        favorite: true,
        image: catPicture,
    },
    {
        id: nanoid(),
        category: 'sell',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute cat looking for a home',
        favorite: false,
        image: catPicture,
    },
    {
        id: nanoid(),
        category: 'sell',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute cat looking for a home',
        favorite: false,
        image: catPicture,
    },
    {
        id: nanoid(),
        category: 'sell',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute cat looking for a home',
        favorite: true,
        image: catPicture,
    },
    {
        id: nanoid(),
        category: 'sell',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute cat looking for a home',
        favorite: true,
        image: catPicture,
    },
    {
        id: nanoid(),
        category: 'sell',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute cat looking for a home',
        favorite: true,
        image: catPicture,
    },
    {
        id: nanoid(),
        category: 'sell',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute cat looking for a home',
        favorite: true,
        image: catPicture,
    },
    {
        id: nanoid(),
        category: 'sell',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute cat looking for a home',
        favorite: false,
        image: catPicture,
    },
    {
        id: nanoid(),
        category: 'sell',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute cat looking for a home',
        favorite: true,
        image: catPicture,
    },
    {
        id: nanoid(),
        category: 'sell',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute cat looking for a home',
        favorite: false,
        image: catPicture,
    },
    {
        id: nanoid(),
        category: 'sell',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute cat looking for a home',
        favorite: true,
        image: catPicture,
    },
    {
        id: nanoid(),
        category: 'sell',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute cat looking for a home',
        favorite: false,
        image: catPicture,
    },
    {
        id: nanoid(),
        category: 'sell',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute cat looking for a home',
        favorite: false,
        image: catPicture,
    },
    {
        id: nanoid(),
        category: 'sell',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute cat looking for a home',
        favorite: true,
        image: catPicture,
    },
    {
        id: nanoid(),
        category: 'sell',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute cat looking for a home',
        favorite: true,
        image: catPicture,
    },
    {
        id: nanoid(),
        category: 'sell',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute cat looking for a home',
        favorite: true,
        image: catPicture,
    },
    {
        id: nanoid(),
        category: 'sell',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute cat looking for a home',
        favorite: true,
        image: catPicture,
    },
    {
        id: nanoid(),
        category: 'sell',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute cat looking for a home',
        favorite: false,
        image: catPicture,
    },
    {
        id: nanoid(),
        category: 'sell',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute cat looking for a home',
        favorite: true,
        image: catPicture,
    },
    {
        id: nanoid(),
        category: 'sell',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute cat looking for a home',
        favorite: false,
        image: catPicture,
    },
    {
        id: nanoid(),
        category: 'sell',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute cat looking for a home',
        favorite: true,
        image: catPicture,
    },
    {
        id: nanoid(),
        category: 'sell',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute cat looking for a home',
        favorite: false,
        image: catPicture,
    },
    {
        id: nanoid(),
        category: 'sell',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute cat looking for a home',
        favorite: false,
        image: catPicture,
    },
    {
        id: nanoid(),
        category: 'sell',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute cat looking for a home',
        favorite: true,
        image: catPicture,
    },
    {
        id: nanoid(),
        category: 'sell',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute cat looking for a home',
        favorite: true,
        image: catPicture,
    },
    {
        id: nanoid(),
        category: 'sell',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute cat looking for a home',
        favorite: true,
        image: catPicture,
    },
];

export default items;
