import { nanoid } from 'nanoid';
import dogPicture from 'images/example/dog.jpg';
import { getRandomValue, favArr } from './getRandomValue';

const items = [
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'in good hands',
        title: 'Cute dog looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: dogPicture,
        favorite: getRandomValue(favArr),
    },
];

export default items;
