import { nanoid } from 'nanoid';
import dogPicture from 'images/example/dog.jpg';

const items = [
    {
        id: nanoid(),
        category: 'in good hands',
        location: 'Lviv',
        age: '1 year',
        sex: 'male',
        title: 'Cute dog looking for a home',
        favorite: false,
        image: dogPicture,
    },
    {
        id: nanoid(),
        category: 'in good hands',
        location: 'Lviv',
        age: '1 year',
        sex: 'male',
        title: 'Cute dog looking for a home',
        favorite: true,
        image: dogPicture,
    },
    {
        id: nanoid(),
        category: 'in good hands',
        location: 'Lviv',
        age: '1 year',
        sex: 'male',
        title: 'Cute dog looking for a home',
        favorite: false,
        image: dogPicture,
    },
    {
        id: nanoid(),
        category: 'in good hands',
        location: 'Lviv',
        age: '1 year',
        sex: 'male',
        title: 'Cute dog looking for a home',
        favorite: true,
        image: dogPicture,
    },
    {
        id: nanoid(),
        category: 'in good hands',
        location: 'Lviv',
        age: '1 year',
        sex: 'male',
        title: 'Cute dog looking for a home',
        favorite: false,
        image: dogPicture,
    },
    {
        id: nanoid(),
        category: 'in good hands',
        location: 'Lviv',
        age: '1 year',
        sex: 'male',
        title: 'Cute dog looking for a home',
        favorite: false,
        image: dogPicture,
    },
    {
        id: nanoid(),
        category: 'in good hands',
        location: 'Lviv',
        age: '1 year',
        sex: 'male',
        title: 'Cute dog looking for a home',
        favorite: true,
        image: dogPicture,
    },
    {
        id: nanoid(),
        category: 'in good hands',
        location: 'Lviv',
        age: '1 year',
        sex: 'male',
        title: 'Cute dog looking for a home',
        favorite: false,
        image: dogPicture,
    },
    {
        id: nanoid(),
        category: 'in good hands',
        location: 'Lviv',
        age: '1 year',
        sex: 'male',
        title: 'Cute dog looking for a home',
        favorite: false,
        image: dogPicture,
    },
    {
        id: nanoid(),
        category: 'in good hands',
        location: 'Lviv',
        age: '1 year',
        sex: 'male',
        title: 'Cute dog looking for a home',
        favorite: true,
        image: dogPicture,
    },
];

export default items;
