import { nanoid } from 'nanoid';
import parrotPicture from 'images/example/parrot.jpg';
import { getRandomValue, favArr } from './getRandomValue';

const items = [
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'lost/found',
        title: 'Cute parrot looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',

        comments: 'Really cute pet',
        image: parrotPicture,
        favorite: getRandomValue(favArr),
    },
];

export default items;
