import { nanoid } from 'nanoid';
import catPicture from 'images/example/cat.jpg';
import { getRandomValue, favArr } from './getRandomValue';

const items = [
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
    {
        id: nanoid(),
        category: 'sell',
        title: 'Cute cat looking for a home',
        name: 'Pet name',
        date: '1 year',
        breed: 'some breed',
        sex: 'male',
        location: 'Lviv',
        price: 100,
        comments: 'Really cute pet',
        image: catPicture,
        favorite: getRandomValue(favArr),
    },
];

export default items;
