import { nanoid } from 'nanoid';
import parrotPicture from 'images/example/parrot.jpg';

const items = [
    {
        id: nanoid(),
        category: 'lost/found',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute parrot looking for a home',
        favorite: true,
        image: parrotPicture,
    },
    {
        id: nanoid(),
        category: 'lost/found',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute parrot looking for a home',
        favorite: false,
        image: parrotPicture,
    },
    {
        id: nanoid(),
        category: 'lost/found',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute parrot looking for a home',
        favorite: true,
        image: parrotPicture,
    },
    {
        id: nanoid(),
        category: 'lost/found',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute parrot looking for a home',
        favorite: false,
        image: parrotPicture,
    },
    {
        id: nanoid(),
        category: 'lost/found',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute parrot looking for a home',
        favorite: true,
        image: parrotPicture,
    },
    {
        id: nanoid(),
        category: 'lost/found',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute parrot looking for a home',
        favorite: false,
        image: parrotPicture,
    },
    {
        id: nanoid(),
        category: 'lost/found',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute parrot looking for a home',
        favorite: false,
        image: parrotPicture,
    },
    {
        id: nanoid(),
        category: 'lost/found',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute parrot looking for a home',
        favorite: true,
        image: parrotPicture,
    },
    {
        id: nanoid(),
        category: 'lost/found',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute parrot looking for a home',
        favorite: true,
        image: parrotPicture,
    },
    {
        id: nanoid(),
        category: 'lost/found',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute parrot looking for a home',
        favorite: true,
        image: parrotPicture,
    },
    {
        id: nanoid(),
        category: 'lost/found',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute parrot looking for a home',
        favorite: true,
        image: parrotPicture,
    },
    {
        id: nanoid(),
        category: 'lost/found',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute parrot looking for a home',
        favorite: false,
        image: parrotPicture,
    },
    {
        id: nanoid(),
        category: 'lost/found',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute parrot looking for a home',
        favorite: true,
        image: parrotPicture,
    },
    {
        id: nanoid(),
        category: 'lost/found',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute parrot looking for a home',
        favorite: false,
        image: parrotPicture,
    },
    {
        id: nanoid(),
        category: 'lost/found',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute parrot looking for a home',
        favorite: true,
        image: parrotPicture,
    },
    {
        id: nanoid(),
        category: 'lost/found',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute parrot looking for a home',
        favorite: false,
        image: parrotPicture,
    },
    {
        id: nanoid(),
        category: 'lost/found',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute parrot looking for a home',
        favorite: false,
        image: parrotPicture,
    },
    {
        id: nanoid(),
        category: 'lost/found',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute parrot looking for a home',
        favorite: true,
        image: parrotPicture,
    },
    {
        id: nanoid(),
        category: 'lost/found',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute parrot looking for a home',
        favorite: true,
        image: parrotPicture,
    },
    {
        id: nanoid(),
        category: 'lost/found',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute parrot looking for a home',
        favorite: true,
        image: parrotPicture,
    },
    {
        id: nanoid(),
        category: 'lost/found',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute parrot looking for a home',
        favorite: true,
        image: parrotPicture,
    },
    {
        id: nanoid(),
        category: 'lost/found',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute parrot looking for a home',
        favorite: false,
        image: parrotPicture,
    },
    {
        id: nanoid(),
        category: 'lost/found',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute parrot looking for a home',
        favorite: true,
        image: parrotPicture,
    },
    {
        id: nanoid(),
        category: 'lost/found',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute parrot looking for a home',
        favorite: false,
        image: parrotPicture,
    },
    {
        id: nanoid(),
        category: 'lost/found',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute parrot looking for a home',
        favorite: true,
        image: parrotPicture,
    },
    {
        id: nanoid(),
        category: 'lost/found',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute parrot looking for a home',
        favorite: false,
        image: parrotPicture,
    },
    {
        id: nanoid(),
        category: 'lost/found',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute parrot looking for a home',
        favorite: false,
        image: parrotPicture,
    },
    {
        id: nanoid(),
        category: 'lost/found',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute parrot looking for a home',
        favorite: true,
        image: parrotPicture,
    },
    {
        id: nanoid(),
        category: 'lost/found',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute parrot looking for a home',
        favorite: true,
        image: parrotPicture,
    },
    {
        id: nanoid(),
        category: 'lost/found',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute parrot looking for a home',
        favorite: true,
        image: parrotPicture,
    },
    {
        id: nanoid(),
        category: 'lost/found',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute parrot looking for a home',
        favorite: true,
        image: parrotPicture,
    },
    {
        id: nanoid(),
        category: 'lost/found',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute parrot looking for a home',
        favorite: false,
        image: parrotPicture,
    },
    {
        id: nanoid(),
        category: 'lost/found',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute parrot looking for a home',
        favorite: true,
        image: parrotPicture,
    },
    {
        id: nanoid(),
        category: 'lost/found',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute parrot looking for a home',
        favorite: false,
        image: parrotPicture,
    },
    {
        id: nanoid(),
        category: 'lost/found',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute parrot looking for a home',
        favorite: true,
        image: parrotPicture,
    },
    {
        id: nanoid(),
        category: 'lost/found',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute parrot looking for a home',
        favorite: false,
        image: parrotPicture,
    },
    {
        id: nanoid(),
        category: 'lost/found',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute parrot looking for a home',
        favorite: false,
        image: parrotPicture,
    },
    {
        id: nanoid(),
        category: 'lost/found',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute parrot looking for a home',
        favorite: true,
        image: parrotPicture,
    },
    {
        id: nanoid(),
        category: 'lost/found',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute parrot looking for a home',
        favorite: true,
        image: parrotPicture,
    },
    {
        id: nanoid(),
        category: 'lost/found',
        location: 'Lviv',
        age: '1 year',
        sex: 'female',
        title: 'Cute parrot looking for a home',
        favorite: true,
        image: parrotPicture,
    },
];

export default items;
